version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - export AWS_SDK_LOAD_CONFIG=1

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ACCOUNT_ID=423623849965
      - REGION=us-east-1
      - IMAGE_TAG=v1.$CODEBUILD_BUILD_NUMBER
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com

  build:
    commands:
      - echo Building cart image...
      - cd src/cart
      - docker build -t cart:${IMAGE_TAG} .
      - docker tag cart:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cart:${IMAGE_TAG}
      - cd -

      - echo Building catalog image...
      - cd src/catalog
      - docker build -t catalog:${IMAGE_TAG} .
      - docker tag catalog:${IMAGE_TAG} ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/catalog:${IMAGE_TAG}
      - cd -

  post_build:
    commands:
      - echo Pushing Docker images...
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cart:${IMAGE_TAG}
      - docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/catalog:${IMAGE_TAG}

      - echo Preparing Kubernetes manifests with updated images...
      - mkdir -p k8s-out

      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cart:${IMAGE_TAG}|g" k8s/cart-deployment.yaml > k8s-out/cart-deployment.yaml
      - sed "s|IMAGE_PLACEHOLDER|${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/catalog:${IMAGE_TAG}|g" k8s/catalog-deployment.yaml > k8s-out/catalog-deployment.yaml
      - cp k8s/ui-deployment.yaml k8s-out/
      - cp k8s/ui-service.yaml k8s-out/

      - echo Deploying to EKS...
      - aws eks update-kubeconfig --region $REGION --name ecommerce-cluster
      - kubectl apply -f k8s-out/

artifacts:
  base-directory: k8s-out
  files:
    - cart-deployment.yaml
    - catalog-deployment.yaml
    - ui-deployment.yaml
    - ui-service.yaml
