apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: 423623849965.dkr.ecr.us-east-1.amazonaws.com/catalog:v1.10
        ports:
        - containerPort: 8080
        env:
        - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
          value: mysql
        - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
          value: RDS_ENDPOINT_REPLACE
        - name: RETAIL_CATALOG_PERSISTENCE_DB_NAME
          value: catalogdb 
        - name: RETAIL_CATALOG_PERSISTENCE_USER
          value: admin
        - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
          value: admin1234

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
spec:
  selector:
    app: catalog
  ports:
    - port: 80       
      targetPort: 8080
  type: LoadBalancer
