apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-ui
  template:
    metadata:
      labels:
        app: store-ui
    spec:
      containers:
      - name: store-ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-ui-svc
spec:
  type: LoadBalancer
  selector:
    app: store-ui
  ports:
  - port: 80
    targetPort: 8080
