# k8s/ui-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: store-ui-svc
  namespace: retail
spec:
  type: LoadBalancer
  selector:
    app: store-ui
  ports:
  - port: 80
    targetPort: 8080
